name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@bf3ba06696b02a028d2121b04961926c1b862a3c
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          gatsby-args: --prefix-paths
          working-dir: docs
