name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    defaults:
      run:
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        working-directory: docs
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          gatsby-args: --prefix-paths
